# Generated by Django 5.2.4 on 2025-07-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='deskripsi',
            field=models.TextField(default='Belum ada deskripsi'),
        ),
        migrations.AddField(
            model_name='produk',
            name='kategori',
            field=models.CharField(default='Umum', max_length=50),
        ),
        migrations.AddField(
            model_name='produk',
            name='kegunaan',
            field=models.CharField(default='Umum', max_length=100),
        ),
    ]
