# Generated by Django 5.2.4 on 2025-09-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produk_deskripsi_produk_kategori_produk_kegunaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='image_path',
            field=models.CharField(default='images/default.png', max_length=255),
        ),
    ]
