# Generated by Django 5.2.4 on 2025-09-10 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produk_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spesifikasi', to='core.produk')),
            ],
        ),
    ]
