# Generated by Django 5.2.4 on 2025-09-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_spesifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
