# Generated by Django 5.2.4 on 2025-09-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produk_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
