# Generated by Django 5.2.4 on 2025-09-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_produk_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='link_shopee',
            field=models.URLField(blank=True, default='https://shopee.co.id/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='link_tokopedia',
            field=models.URLField(blank=True, default='https://www.tokopedia.com/', max_length=255, null=True),
        ),
    ]
