# Generated by Django 5.2.4 on 2025-09-12 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_produk_link_shopee_produk_link_tokopedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('keterangan', models.CharField(max_length=100)),
                ('result', models.IntegerField(default=0)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='core.produk')),
            ],
        ),
        migrations.CreateModel(
            name='Keunggulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keunggulan', to='core.produk')),
            ],
        ),
        migrations.CreateModel(
            name='Performa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=50)),
                ('performance', models.IntegerField(default=0)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performas', to='core.produk')),
            ],
        ),
        migrations.CreateModel(
            name='PerformaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=255)),
                ('performa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.performa')),
            ],
        ),
        migrations.CreateModel(
            name='PerformaResolusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deskripsi', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=50)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performa_resolusi', to='core.produk')),
            ],
        ),
    ]
